#生产环境启动配置 java -jar -Dspring.profiles.active=prod
swagger:
  enable: false

file:
  #服务器文件上传地址
  localUrl: "/root/upload/images/"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?useSSL=false&allowPublicKeyRetrieval=true
            &useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: wiki
    password: '@wiki'
    driver-class-name: com.mysql.cj.jdbc.Driver


